version: 2
jobs:
  build:
    working_directory: ~/ktor-prometheus-feature
    docker:
      - image: gradle:4.0-jdk8
    steps:
      - checkout
      - restore_cache:
          key: circleci-ktor-prometheus-feature-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-ktor-prometheus-feature-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: gradle test
